name: Sync With Hugging Face Hub
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.1
            - name: Set up Cache
              uses: actions/cache@v4.1.2
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/.gitignore') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Sync With Hugging Face Hub
              uses: nateraw/huggingface-sync-action@v0.0.5
              with:
                  github_repo_id: "MH0386/napoleon_dataset"
                  huggingface_repo_id: "MH0386/napoleon_bonaparte"
                  hf_token: ${{ secrets.HF_TOKEN }}
                  repo_type: "dataset"
